# @package _global_
# API endpoint defaults

# llm_base_url: http://localhost:8777/v1
# model_name: Qwen3-235B-A22B-Thinking-2507

llm_base_url: https://openrouter.ai/api/v1
model_name: google/gemini-3-flash-preview
# model_name: qwen/qwen3-235b-a22b
# model_name: openai/gpt-oss-120b
# model_name: openai/gpt-5.4-mini
# model_name: qwen/qwen3.5-397b-a17b
# model_name: deepseek/deepseek-v3.2
