"""Build the paper-update report from the full90 head-to-head + the VAL sweeps.

Inputs (all optional except --results-dir):
  --results-dir   dir with squeeze_<name>.json for champion / E7 / E8 (full90 TEST)
  --sweep-shape   sweep_shape.json   (stage-1 M x sigma grid on panel)
  --sweep-budget  sweep_budget.json  (stage-2 R x fresh_every grid on panel)
  --packings      packings_champion.npz (champion best codes; for tail plot)

Outputs (to --out-dir):
  table_full90.tex        90-row Cohn | E7 | E8 | champion table, bold = beats Cohn
  fig_perdim_gain.png     per-dimension mean rel-improvement, grouped bars
  fig_gain_sorted.png     per-config champion gain, sorted (where it beats Cohn)
  fig_sweep_shape.png     M x sigma panel-gain heatmap (if sweep-shape given)
  fig_sweep_budget.png    R x fresh_every panel-gain heatmap (if sweep-budget given)
  fig_tail_<d>_<n>.png    inner-product right tail, Cohn vs champion (flagship config)
  report.md               narrative: headline numbers + figure index

Run with the isolated venv python (has matplotlib):
  /tmp/umap_venv/bin/python make_report.py --results-dir squeeze_test ...
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

_PROB = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _PROB)

plt.rcParams.update(
    {
        "figure.dpi": 130,
        "savefig.dpi": 130,
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
    }
)

_COLORS = {"champion": "#d1495b", "E7": "#2e86ab", "E8": "#5b8c5a", "Cohn": "#8d8d8d"}


def _load_prog(results_dir: Path, name: str) -> dict | None:
    p = results_dir / f"squeeze_{name}.json"
    if not p.exists():
        return None
    d = json.loads(p.read_text())
    d["by_cfg"] = {(r["d"], r["n"]): r for r in d["results"]}
    return d


def _fmt(mu: float, mu_cohn: float, improved: bool) -> str:
    s = f"{mu:.6f}"
    if not improved:
        return s
    c = f"{mu_cohn:.6f}"
    i = 0
    while i < len(s) and i < len(c) and s[i] == c[i]:
        i += 1
    return s[:i] + rf"\textbf{{{s[i:]}}}" if i < len(s) else s


def build_table(
    progs: dict[str, dict], order: list[str], out: Path
) -> dict[str, float]:
    """Write the 90-row TeX table; return per-program avg rel improvement %."""
    ref = progs[order[0]] if order else None
    # configs sorted by (d, n) from any available program
    any_prog = next(iter(progs.values()))
    cfgs = sorted(any_prog["by_cfg"].keys())

    cols = [c for c in ["E7", "E8", "champion"] if c in progs]
    lines = [
        r"% auto-generated by make_report.py -- do not edit by hand",
        r"\begin{tabular}{rr" + "r" * (1 + len(cols)) + "}",
        r"\toprule",
        r"$d$ & $N$ & $\mu_{\mathrm{Cohn}}$ & "
        + " & ".join(rf"$\mu_{{\mathrm{{{c}}}}}$" for c in cols)
        + r" \\",
        r"\midrule",
    ]
    avg: dict[str, list[float]] = {c: [] for c in cols}
    nimp: dict[str, int] = {c: 0 for c in cols}
    for d, n in cfgs:
        mu_cohn = None
        cells = []
        for c in cols:
            r = progs[c]["by_cfg"].get((d, n))
            if r is None:
                cells.append("--")
                continue
            mu_cohn = r["mu_cohn"]
            imp = r["mu_best"] < mu_cohn - 1e-15
            cells.append(_fmt(r["mu_best"], mu_cohn, imp))
            g = max(0.0, (mu_cohn - r["mu_best"]) / (abs(mu_cohn) or 1.0))
            avg[c].append(g)
            if imp:
                nimp[c] += 1
        cohn_str = f"{mu_cohn:.6f}" if mu_cohn is not None else "--"
        lines.append(f"{d} & {n} & {cohn_str} & " + " & ".join(cells) + r" \\")
    lines.append(r"\midrule")

    summary = {c: 100.0 * float(np.mean(avg[c])) if avg[c] else 0.0 for c in cols}
    imp_cells = " & ".join(
        rf"{summary[c]:.4f}\% ({nimp[c]}/{len(avg[c])})" for c in cols
    )
    lines.append(
        r"\multicolumn{3}{r}{\emph{mean rel.\ improvement (\# improved)}} & "
        + imp_cells
        + r" \\"
    )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    out.write_text("\n".join(lines))
    return summary


def fig_perdim(progs: dict[str, dict], order: list[str], out: Path) -> None:
    cols = [c for c in order if c in progs]
    dims = sorted({d for p in progs.values() for (d, _) in p["by_cfg"]})
    x = np.arange(len(dims))
    w = 0.8 / max(1, len(cols))
    fig, ax = plt.subplots(figsize=(8, 4))
    for i, c in enumerate(cols):
        vals = []
        for d in dims:
            rows = [r for (dd, _), r in progs[c]["by_cfg"].items() if dd == d]
            g = 100.0 * np.mean(
                [
                    max(0.0, (r["mu_cohn"] - r["mu_best"]) / (abs(r["mu_cohn"]) or 1.0))
                    for r in rows
                ]
            )
            vals.append(g)
        ax.bar(x + i * w - 0.4 + w / 2, vals, w, label=c, color=_COLORS.get(c, None))
    ax.set_xticks(x)
    ax.set_xticklabels(dims)
    ax.set_xlabel("dimension $d$")
    ax.set_ylabel("mean rel. improvement over Cohn (%)")
    ax.set_title("Per-dimension improvement over the Cohn catalogue")
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)


def fig_gain_sorted(progs: dict[str, dict], out: Path) -> None:
    if "champion" not in progs:
        return
    rows = list(progs["champion"]["by_cfg"].values())
    gains = sorted(
        (
            100.0 * max(0.0, (r["mu_cohn"] - r["mu_best"]) / (abs(r["mu_cohn"]) or 1.0))
            for r in rows
        ),
        reverse=True,
    )
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(np.arange(len(gains)), gains, color=_COLORS["champion"], width=1.0)
    ax.set_xlabel("config rank (by improvement)")
    ax.set_ylabel("rel. improvement over Cohn (%)")
    n_improved = sum(
        p.get("improved", False) for p in progs["champion"]["by_cfg"].values()
    )
    ax.set_title(
        f"Champion per-config improvement (full90), {n_improved}/{len(gains)} improved"
    )
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)


def _heatmap_from_sweep(sweep: dict, row_key, col_key, out: Path, title: str) -> None:
    cells = sweep["cells"]
    rows = sorted({row_key(c) for c in cells})
    colv = sorted({col_key(c) for c in cells})
    M = np.full((len(rows), len(colv)), np.nan)
    for c in cells:
        i = rows.index(row_key(c))
        j = colv.index(col_key(c))
        M[i, j] = c["best_over_seeds_mean_pct"]
    fig, ax = plt.subplots(figsize=(1.6 + 1.1 * len(colv), 1.6 + 0.7 * len(rows)))
    im = ax.imshow(M, aspect="auto", cmap="viridis")
    ax.set_xticks(range(len(colv)))
    ax.set_xticklabels(colv, rotation=30, ha="right")
    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels(rows)
    for i in range(len(rows)):
        for j in range(len(colv)):
            if not np.isnan(M[i, j]):
                ax.text(
                    j,
                    i,
                    f"{M[i, j]:.3f}",
                    ha="center",
                    va="center",
                    color="w",
                    fontsize=8,
                )
    fig.colorbar(im, ax=ax, label="panel mean gain (best/seed, %)")
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)


def _parse_cell_label(label: str) -> dict:
    # R{r}_M{m}_hi{hi}_lo{lo}_fe{fe}
    out = {}
    for tok in label.split("_"):
        for k in ("R", "M", "hi", "lo", "fe"):
            if (
                tok.startswith(k)
                and tok[len(k) :]
                .replace(".", "")
                .replace("e", "")
                .replace("-", "")
                .replace("+", "")
                .isalnum()
            ):
                out[k] = tok[len(k) :]
    return out


def fig_sweep_shape(sweep: dict, out: Path) -> None:
    for c in sweep["cells"]:
        c["_p"] = _parse_cell_label(c["cell"])
    _heatmap_from_sweep(
        sweep,
        row_key=lambda c: f"M={c['_p'].get('M', '?')}",
        col_key=lambda c: f"{c['_p'].get('hi', '?')}:{c['_p'].get('lo', '?')}",
        out=out,
        title="Stage-1 shape sweep (panel): noising steps M x sigma schedule",
    )


def fig_sweep_budget(sweep: dict, out: Path) -> None:
    for c in sweep["cells"]:
        c["_p"] = _parse_cell_label(c["cell"])
    _heatmap_from_sweep(
        sweep,
        row_key=lambda c: f"R={c['_p'].get('R', '?')}",
        col_key=lambda c: f"fe={c['_p'].get('fe', '?')}",
        out=out,
        title="Stage-2 budget sweep (panel): restarts R x fresh_every",
    )


def fig_tail(
    packings: Path, flagship: list[tuple[int, int]], out_dir: Path
) -> list[str]:
    import cohn_catalogue as cc

    z = np.load(packings)
    made = []
    for d, n in flagship:
        key = f"{d}_{n}"
        if key not in z.files:
            continue
        Xc, _ = cc.load_frozen(d, n)
        Xe = np.asarray(z[key], dtype=np.float64)

        def offdiag(X):
            G = X @ X.T
            iu = np.triu_indices(X.shape[0], k=1)
            return G[iu]

        gc, ge = offdiag(Xc), offdiag(Xe)
        muc, mue = gc.max(), ge.max()
        lo = min(np.quantile(gc, 0.995), np.quantile(ge, 0.995))
        hi = max(muc, mue)
        bins = np.linspace(lo, hi * 1.0005, 60)
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.hist(gc, bins=bins, alpha=0.55, label="Cohn", color=_COLORS["Cohn"])
        ax.hist(
            ge,
            bins=bins,
            alpha=0.55,
            label="ImprovEvolve (champion)",
            color=_COLORS["champion"],
        )
        ax.axvline(muc, color=_COLORS["Cohn"], ls="--", lw=1.5)
        ax.axvline(mue, color=_COLORS["champion"], ls="--", lw=1.5)
        ax.set_xlabel(r"pairwise inner product $\langle x_i, x_j\rangle$")
        ax.set_ylabel("count")
        ax.set_title(f"(d={d}, N={n}) right tail:  $\\mu$ {muc:.5f} $\\to$ {mue:.5f}")
        ax.legend(frameon=False)
        fig.tight_layout()
        p = out_dir / f"fig_tail_{d}_{n}.png"
        fig.savefig(p)
        plt.close(fig)
        made.append(p.name)
    return made


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--sweep-shape", default=None)
    ap.add_argument("--sweep-budget", default=None)
    ap.add_argument("--packings", default=None)
    ap.add_argument(
        "--flagship",
        default=None,
        help="comma d:n list for tail plots; default = top champion gains",
    )
    ap.add_argument("--out-dir", default="report")
    args = ap.parse_args()

    results_dir = Path(args.results_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    progs = {}
    for name in ("E7", "E8", "champion"):
        p = _load_prog(results_dir, name)
        if p is not None:
            progs[name] = p
    if not progs:
        raise SystemExit(f"no squeeze_*.json under {results_dir}")
    order = [c for c in ("E7", "E8", "champion") if c in progs]

    summary = build_table(progs, order, out_dir / "table_full90.tex")
    fig_perdim(progs, order, out_dir / "fig_perdim_gain.png")
    fig_gain_sorted(progs, out_dir / "fig_gain_sorted.png")

    figs = ["fig_perdim_gain.png", "fig_gain_sorted.png"]
    if args.sweep_shape and Path(args.sweep_shape).exists():
        fig_sweep_shape(
            json.loads(Path(args.sweep_shape).read_text()),
            out_dir / "fig_sweep_shape.png",
        )
        figs.append("fig_sweep_shape.png")
    if args.sweep_budget and Path(args.sweep_budget).exists():
        fig_sweep_budget(
            json.loads(Path(args.sweep_budget).read_text()),
            out_dir / "fig_sweep_budget.png",
        )
        figs.append("fig_sweep_budget.png")

    flagship = []
    if args.flagship:
        flagship = [
            (int(a), int(b))
            for a, b in (tok.split(":") for tok in args.flagship.split(","))
        ]
    elif "champion" in progs:
        rows = sorted(
            progs["champion"]["by_cfg"].values(),
            key=lambda r: max(
                0.0, (r["mu_cohn"] - r["mu_best"]) / (abs(r["mu_cohn"]) or 1.0)
            ),
            reverse=True,
        )
        flagship = [(r["d"], r["n"]) for r in rows[:4]]
    if args.packings and Path(args.packings).exists():
        figs += fig_tail(Path(args.packings), flagship, out_dir)

    md = ["# Spherical-codes improver — paper-update report", ""]
    md.append("## Headline (full90 TEST, mean rel. improvement over Cohn)")
    md.append("")
    md.append("| program | mean rel. improvement | improved configs | valid |")
    md.append("|---|---|---|---|")
    for c in order:
        d = progs[c]
        md.append(
            f"| {c} | {summary[c]:.4f}% | {d['improved']}/{len(d['results'])} | {d['valid']}/{len(d['results'])} |"
        )
    md.append("")
    md.append("## Figures")
    for f in figs:
        md.append(f"- `{f}`")
    md.append("")
    md.append("Table: `table_full90.tex` (90 rows, bold = beats Cohn).")
    (out_dir / "report.md").write_text("\n".join(md))

    print("REPORT OK ->", out_dir)
    for c in order:
        print(
            f"  {c}: {summary[c]:.4f}%  improved {progs[c]['improved']}/{len(progs[c]['results'])}"
        )
    print("  figs:", figs)


if __name__ == "__main__":
    main()
